- cypress/integration/exchange.js
- src/containers/exchange/components/PlaceOrderForm.js
exchange: entering AEUR amount on 99% rate results different A-EUR on form than entering the calculated ETH
> [exchaneg] calculation bugfix

- package.json
- src/.eslintrc
- src/components/navigation/index.js
- src/containers/account/components/TransferList.js
- src/containers/lock/components/ReleaseFundsButton.js
- yarn.lock
1. After `git commit` changes:
- ~run eslint against the `/src` folder~
- run prettier against the whole repo and fix forward mismatching coding style
2. Add `"no-unused-vars": "error"` rule to `.eslintrc` to throw error instead of warning which we tend to overlook
> Add precommit hook

- src/containers/home/tryIt/TryItConnected.js
- go to augmint.cc/tryit
- rinkeby.io & discord links in `Get some test ETH` section will NOT work
- [Trello card](https://trello.com/c/ia9cCpth)
> fix(TryItConnected): change <Link> to </a>

- src/containers/home/tryIt/HowToConnect.js
- src/containers/home/tryIt/TryItConnected.js
- see yarn start log for messages
> fix(tryIt): add rel='noopener noreferrer' to 3 links

- cypress/integration/augmintbasic.js
- src/containers/app/index.js
You need a user who has old contracts a-euro/loan/lock then go to reserves/underthehood page
https://trello.com/c/cwFbl8d7/141-dont-show-message-alerts-on-reserves-and-underthehood-pages
> don't show message alerts on reserves and underthehood pages

- src/components/hash/index.js
- src/containers/transfer/components/TokenTransferForm.js
- src/containers/transfer/components/TransferRequest.js
- src/containers/transfer/components/TransferRequestAlert.js
- src/containers/transfer/components/TransferRequestHelper.js
https://trello.com/c/OlMPhBsR/245-transfer-request-improvements
- allow query params in notify_url. We append our params if there is any the notify_url (and we override if there is one with the same name)
- transfer/request validations:
- network_id only 1 (mainnet) or 4 (rinkeby) allowed, default: 1.  Showing invalid param error otherwise.
- currency_code must be AEUR, default is AEUR. Invalid param error otherwise
- unique request check extended, we check beneficiary_address, amount, network_id and currency_code (eg. if the transfer happens on different network than the requested network_id then there is no callback)
- when displaying beneficiary_address etherscan link points to network which was requested
> fix(transfer): fix transfer request validation

- src/containers/loan/components/LoanList.js
- src/containers/loan/loanList/index.js
- src/containers/lock/components/LockList.jsx
- src/containers/lock/lockList/index.js
Sorting of locks/loans by release/due date on My account page and locks/loan pages.
go to augmin.org/loan OR /lock OR /account to see broken sorting of locks & loans
> fix(loan, lock): sorting

- src/components/accountInfo/styles.js
- src/components/dashboard/containers/topNav/styles.js
go to augmint.org on mobile/tablet screen size and open the accountInfoPanel from the topNav
> fix(topNav, accountInfo): accountInfoPanel close btn @ < tablet

- src/components/augmint-ui/icon/index.js
- src/components/hash/index.js
- src/containers/PageNotFound.js
- src/containers/account/components/NoTokenAlert.js
- src/containers/app/EthereumState.js
- src/containers/app/index.js
- src/containers/transfer/components/TokenTransferForm.js
- src/containers/transfer/index.js
- src/containers/transfer/request/CreateTransferRequest.js
- src/containers/transfer/request/ShowTransferRequest.js
- src/containers/transfer/request/TransferRequestAlert.js
- src/containers/transfer/request/TransferRequestHelper.js
- src/modules/ethereum/ethHelper.js
- src/modules/ethereum/transferTransactions.js
- src/modules/reducers/augmintToken.js
- src/modules/reducers/submittedTransactions.js
- src/utils/constants.js
- src/utils/helpers.js
- Transfer request is a separate page now (instead of a prepopulated transfer form)
- Redirect user back to store only after 5 network confirmations
- Fix etherscan links (e.g. in transfer history)
- Validate `beneficiary_address` format on transfer request
- Transfer request page shown even when not connected (with link to how to connect page)
- Don't allow to complete transfer request on other network than it was requested
- Show a warning to user that double check the address on transfer request
- Inform user that they will redirected back to store after successful transfer
Example request url:
/transfer/request?order_id=123&token=abc&network_id=4&beneficiary_address=0xa7ab07ffd413d467541ad3f31bf7102eab465e9b&beneficiary_name=Example%20Store&amount=10.2&currency_code=AEUR&reference=test …
> feat(transfer): transfer request improvements

- package.json
- yarn.lock
refershing stability dashboard occasionally results  NaNs in some fields. The error in console (visible when ran in development mode):
`Error: Returned values aren't valid, did it run Out of Gas?`
Fix in web3 beta is on the way, until then downgrade to web 3 beta 35 seems to solve the issue.
Follow [this bug](https://github.com/ethereum/web3.js/issues/1916)
- [x ] Rinkeby
- [x ] Main Ethereum Network
> downgrade to web3 beta 35 due to a bug

- src/containers/augmintToken/index.js
- src/containers/augmintToken/styles.js
- src/containers/transfer/components/TokenTransferForm.js
- src/modules/ethereum/metricsTransaction.js
- src/modules/reducers/monetarySupervisor.js
on the netlify link go to /transfer on both the main & rinkeby network and check out the fee under the amount field.
https://trello.com/c/3nOFeBq2
> don't display Transfer fee when no transfer fee set

- .travis.yml
- cypress/support/index.js
- package.json
- yarn.lock
Attempt to resolve frequent yarn.lock merge conflicts with greenkeeper PR-s.
Switched to Xenial distro on travis. 
Make sure you always use the same yarn version locally as Travis Xenial build. Currently 1.13.0
> Travis to use latest yarn

- src/modules/reducers/submittedTransactions.js
Start a transaction. Dismiss popup notifications. Check if successPanel popup become visible.
https://trello.com/c/neivtoIU
> always show success tx

- src/components/dashboard/containers/topNav/index.js
- src/containers/exchange/components/ExchangeSummary.js
- src/containers/exchange/components/ExchangeToolTips.js
- src/containers/exchange/components/MyOrders.js
- src/containers/exchange/components/OrderBook.js
- src/containers/exchange/components/TradeHistory.js
- src/containers/loan/components/LoanToolTips.js
- src/containers/loan/newLoan/NewLoanForm.js
- src/containers/underthehood/components/RatesInfo.js
- src/modules/ethereum/tradeTransactions.js
- src/utils/constants.js
go to /exchange
- change ETH/€ to ETHEUR
- and correct the (effective) rate:
> fix(exchange): fix rate displayed in oder history + change ETH/€ to ETHEUR

- package.json
- src/components/Disclaimer.js
- src/components/augmint-ui/modal/styles.js
- src/modules/store/index.js
https://trello.com/c/1IhZpa7S
- add `overflow:auto` to ModalContent
- fix `for` console error
- fix `window.devToolsExtension` console warning (Redux DevTools)
> fix(Disclaimer): add overflow & change for to htmlFor

- src/containers/augmintToken/index.js
- src/containers/loan/components/LoanProductDetails.js
- src/containers/lock/components/LockDetails.js
- src/containers/lock/containers/LockForm/index.js
- src/containers/lock/lockList/LockCard.js
- src/modules/ethereum/loanTransactions.js
- src/modules/ethereum/lockTransactions.js
Fixed interest pa. calculation for loan products on stability dashboard. 
Also refactored that interest p.a. % is calculated by reducers (`interestRatePaPt`) for both loan and lock products, saved to store and all components are using that instead of each calculating with their own formula.
Interest rate for lock is incorrectly rounded on stability dashboard
> loan & lock products interest rate rounding fix on stability dashboard

- src/containers/lock/lockList/LockCard.js
Lock interest displayed incorrectly on lock card
> fix lock interest pa. display

- src/modules/ethereum/exchangeTransactions.Matching.test.js
- src/modules/ethereum/exchangeTransactions.js
calculateMatchingOrders fx returned values in inconsistent format  in case when were no orders on any side of the OrderBook. 
It didn't affect the UI because the match orders button is not shown when there are no orders.
N/A
> fix calculateMatchingOrders return when no orders (didn't aff. UI)

- .travis.yml
- travis builds fail bc cypress runs with `runrecord` but can not record more sessions
> fix(travis & cypress): change yarn to don't run record

- package.json
- yarn.lock
This is a (hopefully) non intrusive addition of `augmint-js` package. First step on a long journey.
For now it only brings the benefit that you won't need to worry about upgrades of the ganache docker containers. Any time `augmint-js` upgraded (via greenkeeper PR) `yarn ganache:start` will start the right version of the ganache container, the right way, specified by `augmint-js`
`yarn ganache:start` now calls new `augmint cli ganache {start|stop}` instead of specifying the whole launch command line (which included the the container version). `augmint-cli` is part of the `augmint-js` package.
`augmint-js` uses a different web3.js version now than  `augmint-web`. It's doesn't affect the bundle size yet because  there is no import of `@augmint/js` in the code yet. We will need to check the …
> add augmint-js package and use augmint-cli

- src/components/dashboard/components/sideNav/index.js
- src/containers/transfer/index.js
- src/containers/transfer/request/ShowTransferRequest.js
change "Transfer A-EUR" to "Send A-EUR"
& add it to the menu...
> Change transfer-aeur naming

- src/modules/ethereum/gas.js
increased gas estimate from 70k to 100k due to occasionally running out of gas on rinkeby (see links in comments)
> update CANCEL_ORDER_GAS estimate

- src/components/dashboard/components/sideNav/index.js
fixes small padding issue of the logo on desktop:
> fix(sideNav): logo padding issue

- src/containers/augmintToken/index.js
- src/containers/augmintToken/styles.js
- src/modules/reducers/rates.js
> feat(augmintToken): add etheur rate to the top of stability board

- src/modules/ethereum/gas.js
increased default gas limit to 250k for repay because 150k gas limit is not enough recently, [repay tx fails](https://etherscan.io/tx/0x6f82dbaef1ab74c515b0205debfa1c2b04c96d4bc911c59f0590b538db0b4f63) 
[tx succeeds](https://etherscan.io/tx/0xa955dd7e2f3948af191ed8912d9a2090fe3ef2971c445b7fddcec4050089a3d7) when gas limit increased but sitll  using only 130k gas.
`¯\_(ツ)_/¯`
> increase gas limit offered for repay
