- contracts/Exchange.sol
- contracts/LoanManager.sol
- contracts/Locker.sol
- contracts/generic/AugmintToken.sol
- contracts/generic/Owned.sol
- contracts/generic/Restricted.sol
- contracts/generic/SystemAccount.sol
- contracts/interfaces/AugmintTokenInterface.sol
- contracts/interfaces/LoanManagerInterface.sol
- contracts/mocks/TokenAceMock.sol
- migrations/5_deploy_TokenAce.js
- migrations/6_deploy_LoanManager.js
- migrations/7_deploy_Exchange.js
- migrations/8_deploy_locker.js
- src/containers/app/EthereumState.js
- src/containers/underthehood/components/Web3ConnectionInfo.js
- src/contractsBuild/owned.json
- src/modules/ethereum/SolidityContract.js
- src/modules/reducers/augmintToken.js
- src/modules/reducers/exchange.js
- src/modules/reducers/loanManager.js
- src/modules/reducers/rates.js
- test/ExchangeMatching.test.js
- test/ExchangeOrders.test.js
- test/helpers/exchangeTestHelper.js
- test/helpers/loanTestHelper.js
- test/helpers/tokenAceTestHelper.js
- test/locker.js
Reverts Augmint/augmint-core#68
accidentally merged to master instead of staging branch
> Revert "Permissions refactor"

- src/components/LinkButtons.js
- src/containers/app/EthereumState.js
- src/containers/home/tryIt/HowToConnect.js
- src/containers/home/tryIt/TryItConnected.js
> [discord_button] change gitter button to discord

- package.json
- src/components/button/styles.js
- src/containers/app/index.js
- src/containers/home/NotConnectedHome/index.js
- src/containers/home/concept/style.css
I managed to over-engineer the sticky behaviour, this refactor makes it cleaner.
> Refactor sticky rail on home page

- src/containers/home/NotConnectedHome/helpers.js
> [home] add Tom's bio

- cypress/.eslintrc
- cypress/.prettierrc
- cypress/integration/augmintbasic.js
- cypress/support/commands.js
- src/components/AccountInfo.js
- src/components/AugmintStats.js
- src/components/MsgPanels.js
- src/components/navigation/index.js
- src/containers/account/TokenTransferForm.js
- src/containers/account/components/TransferList.js
- src/containers/augmintToken/index.js
- src/containers/home/tryIt/TryItConnected.js
- src/containers/loan/collectLoan/CollectLoanButton.js
- src/containers/loan/components/LoanList.js
- src/containers/loan/components/LoanRepayLink.js
- src/containers/loan/components/LoansToCollectList.js
- src/containers/loan/newLoan/LoanProductSelector.js
- src/containers/loan/newLoan/NewLoanForm.js
- src/containers/loan/newLoan/NewLoanPage.js
- src/containers/loan/repayLoan/RepayLoanPage.js
- src/containers/underthehood/components/ContractBaseInfo.js
- src/containers/underthehood/components/UserAccountInfo.js
- src/containers/underthehood/components/Web3ConnectionInfo.js
- src/containers/underthehood/index.js
- token transfer test
- use of data-testid everywhere
- speed up tests 
- no snapshot revert before each so we don't need reload every time
- less loan creation (using issueTo helper instead)
- test code refactor (more readable using aliases etc.)
- prettier settings and code reformat (print-width to 120)
> Cypress tests

- package.json
- yarn.lock
remove cross-env package (to run the developer environment in Windows)
> remove cross-env package

- src/components/button/styles.js
- src/components/navigation/index.js
- src/components/navigation/styles.js
- src/containers/app/index.js
- src/containers/home/NotConnectedHome/helpers.js
- src/containers/loan/newLoan/NewLoanForm.js
- src/containers/roadmap/style.js
- src/modules/ethereum/exchangeTransactions.js
- src/modules/ethereum/loanTransactions.js
- src/modules/reducers/loanManager.js
- src/modules/reducers/monetarySupervisor.js
- src/modules/reducers/rates.js
- src/modules/reducers/userBalances.js
- src/utils/constants.js
- removing redundant relative path since every import is relative to `/src` because the [`.env`](https://github.com/Augmint/augmint-web/blob/staging/.env#L1)
- introducing `ONE_ETH_IN_WEI` _(I was getting lost counting ETH<->WEI zeros_):
```
1e18 === 1000000000000000000
```
> Minor refactor

- src/containers/home/tryIt/TryItConnected.js
Change gitter link to discord on try it page
> [tryit] change gitter link to discord

- cypress/integration/exchange.js
> [exchange test] exchange test fix

- cypress/integration/augmintbasic.js
- src/components/navigation/index.js
- src/containers/app/AppFooter.js
- src/containers/app/custom_footer_style.css
- src/containers/app/index.js
- src/containers/exchange/components/TradeHistory.js
https://trello.com/c/V1ye4GdN/61-place-under-the-hood-link-to-the-footer
> Expose /under-the-hood link on frontend

- src/modules/services/featureService/index.js
Setting cookie based version flags for branching features.
Add arbitrary string to the url using the formula below:
**feature name:** `version1`
**url param:** `?f_version1=true`
the service uses [React's context API](https://reactjs.org/docs/context.html)
1. import the `FeatureContext` from the service
`import { FeatureContext } from "modules/services/featureService";`
2. wrap the given feature for branching 
```
<FeatureContext.Consumer>
{features => feature.version1 ? <Version1 /> : <Fallback/>}
</FeatureContext.Consumer>
```
[See wip dashboard changes for example](https://github.com/Augmint/augmint-web/compare/feature-flag?expand=1)
@Augmint/frontend fyi
> Feature flag service

- public/index.html
> Og meta tweaks

- src/containers/augmintToken/components/LtdStats.js
- src/containers/loan/index.js
- src/containers/lock/index.js
- src/modules/loanManagerProvider.js
- src/modules/lockManagerProvider.js
-maxlockable should refresh when new loan taken
-maxlockable should refresh when loan repaid
-maxlockable should refresh when loan defaults
-maxloan should refresh after new lock
-maxloan should refresh when lock released
> Max lock max loan update issue

- .env
- src/components/ExchangeLinks.js
- src/containers/app/EthereumState.js
- src/containers/exchange/components/FiatExchange.js
- src/containers/exchange/index.js
- src/containers/home/tryIt/TryItConnected.js
- src/containers/home/tryIt/index.js
enabling mainnet without feature flag + adjusting / tweaking try it pages
> Enable mainnet

- cypress/integration/loans.js
- cypress/integration/locks.js
- src/modules/ethereum/loanTransactions.js
- src/utils/constants.js
@szerintedmi pls check if i got it right what the task was about.:
- i increased the min loan amount to 110% (11A€).
> fix(loanTransactions): min loan amount adjustment on UI (25%)

- public/_redirects
https://trello.com/c/F1yg9UE7/180-augmint-icon-broken-w-new-dashboard
> redirect nested asset urls

- src/containers/home/tryIt/HowToConnect.js
Disable the metamask
https://trello.com/c/iw3Qrmnl/220-metamask-link-issue
No
> [howToConnect] metamask link element fix

- cypress/integration/loans.js
- src/components/augmint-ui/RadioInput/index.jsx
- src/components/augmint-ui/RadioInput/styles.js
- src/components/hash/index.js
- src/components/portals/TopNavTitlePortal.js
- src/components/toolTip/index.js
- src/components/toolTip/styles.js
- src/containers/loan/components/LoanProductDetails.js
- src/containers/loan/components/LoanProductList.js
- src/containers/loan/newLoan/LoanProductSelector.js
- src/containers/loan/newLoan/NewLoanForm.js
- src/containers/loan/newLoan/NewLoanPage.js
- src/containers/loan/newLoan/index.js
https://trello.com/c/T3Aq0nvo/212-new-loan-flow-refactor-as-one-page
https://cdn.discordapp.com/attachments/439446822063308810/461443391109201941/augmint-loan-screen.png
Yes, and does not matter which one.
> Loan refactor

- package.json
- yarn.lock
> fix(package): update styled-tools to version 0.6.2

- cypress/integration/loans.js
- src/components/Icons.js
- src/components/PageLayout.js
- src/components/augmint-ui/button/styles.js
- src/components/augmint-ui/container/styles.js
- src/components/augmint-ui/modal/styles.js
- src/components/dashboard/components/sideNav/index.js
- src/components/dashboard/containers/topNav/styles.js
- src/components/navigation/index.js
- src/components/navigation/styles.js
- src/containers/exchange/components/CancelOrderButton.js
- src/containers/exchange/components/TradeHistory.js
- src/containers/home/NotConnectedHome/index.js
- src/containers/loan/collectLoan/index.js
- src/containers/loan/loanDetailsPage.js
- src/containers/loan/repayLoan/RepayLoanPage.js
- src/containers/lock/containers/LockForm/index.js
- src/containers/lock/containers/LockForm/styles.js
- src/containers/underthehood/AugmintInfoGroup.js
- src/containers/underthehood/BaseInfoGroup.js
- src/containers/underthehood/ExchangeInfoGroup.js
- src/containers/underthehood/LoansInfoGroup.js
- src/containers/underthehood/LocksInfoGroup.js
- src/containers/underthehood/PreTokenInfoGroup.js
- src/containers/underthehood/StabilityBoardInfoGroup.js
- src/containers/underthehood/index.js
...
- [Trello card](https://trello.com/c/VmpI9KVT)
> Res content blocks

- cypress/integration/transfers.js
- src/components/Table/style.js
- src/components/augmint-ui/button/styles.js
- src/components/transaction/index.js
- src/containers/account/components/TransferList.js
- src/containers/account/index.js
- src/containers/app/index.js
- src/containers/lock/components/LockList.jsx
- src/containers/transfer/components/AccountToolTips.js
- src/containers/transfer/components/TokenTransferForm.js
- src/containers/transfer/index.js
- src/styles/global.js
- src/styles/media.js
- src/styles/theme.js
go to account page
https://trello.com/c/uk1I2HhG/207-refactor-transaction-history-as-new-wireframe
> Transfer history

- src/components/augmint-ui/header/styles.js
- src/containers/account/index.js
- src/containers/augmintToken/index.js
- src/containers/exchange/index.js
- src/containers/home/tryIt/index.js
- src/containers/loan/collectLoan/index.js
- src/containers/loan/loanDetailsPage.js
- src/containers/loan/newLoan/index.js
- src/containers/loan/repayLoan/index.js
- src/containers/lock/index.js
- src/containers/transfer/index.js
- src/containers/underthehood/index.js
- [Trello card](https://trello.com/c/DYyJkSDA)
> refactor(header): add .nav to H1's in TopNavTitlePortal & to HeaderH1

- package.json
- yarn.lock
https://github.com/ethereum/web3.js/releases/tag/v1.0.0-beta.35
> update web3 package

- src/modules/ethereum/exchangeTransactions.js
go to buy/sell page and check the order book panel
https://trello.com/c/0wXzOjJX/234-exchange-transaction-sort-issue
> order sort fix

- src/components/augmint-ui/button/styles.js
- src/containers/account/components/Balance.js
- src/containers/account/index.js
- src/containers/app/site.css
- src/styles/global.js
- src/styles/theme.js
Go to account page and check the balance card
https://trello.com/c/ZzuY69yw/236-add-balance-card-to-account-page
> feat(account): add balance card to account page

- src/containers/loan/newLoan/NewLoanForm.js
- src/containers/lock/containers/LockForm/index.js
- src/modules/reducers/locks.js
- src/modules/reducers/preToken.js
- src/modules/reducers/stabilityBoardProxy.js
sorting of displayed items was wrong in certain cases:
- loan & lock products on new loan/lock form
- locks
- [x ] local RPC
> sorting fixes

- package.json
- yarn.lock
> Greenkeeper/react tooltip 3.8.0

- package.json
- yarn.lock
> Greenkeeper/styled tools 1.5.1

- src/components/ExchangeLinks.js
- src/components/augmint-ui/button/styles.js
- src/containers/account/HowToGet.js
- src/containers/account/components/NoTokenAlert.js
- src/containers/account/index.js
- src/containers/app/index.js
- src/containers/lock/index.js
- src/containers/transfer/index.js
Navigate to: `/how-to-get` url
https://www.figma.com/proto/D0jGfrRBMnDOHrvcAW2aU5/Augmint.wireframe-(Copy)?node-id=398%3A2&scaling=min-zoom
> feat(account) how to get aeur page

- package.json
- yarn.lock
> Greenkeeper/styled components 3.4.9

- cypress.json
- package.json
- src/modules/reducers/rates.js
- yarn.lock
> Update web3 to beta36

- package.json
- yarn.lock
> Greenkeeper/ethers 3.0.29

- src/components/BaseComponents.js
- src/containers/app/index.js
- src/containers/transfer/components/TokenTransferForm.js
- src/containers/transfer/components/TransferRequest.js
- src/containers/transfer/components/TransferRequestAlert.js
- src/containers/transfer/components/TransferRequestHelper.js
- src/utils/cookie.js
- Go to: `/transfer/request?order_id=123&token=abc&network_id=rinkeby&beneficiary_address=0xa7ab07ffd413d467541ad3f31bf7102eab465e9b&beneficiary_name=Example%20Store&amount=10.2&currency_code=AEUR&reference=test%20transfer&notify_url=https://www.augmint.org`
> feat(transfer): add transfer request handling

- src/modules/ethereum/transferTransactions.js
enter 10.2 to amount field on /transfer form results tx submission failing (see screenshot).
It's a regression likely because of web3 update to beta36
> fix js float issue for transfer amount

- package.json
- yarn.lock
> Greenkeeper/husky 1.0.1

- src/components/accountInfo/styles.js
- src/components/dashboard/containers/topNav/styles.js
- src/containers/account/HowToGet.js
- src/containers/account/components/NoTokenAlert.js
- src/containers/exchange/index.js
- src/containers/home/tryIt/TryItConnected.js
- src/containers/loan/index.js
- src/containers/lock/index.js
- src/containers/lock/newLock/index.js
- added text on /how-to-get and /tryit pages that ETH is needed to send transactions
- added an alert that you need ETH to send transactions when user has A-EUR but 0 ETH balance (when the user has no A-EUR we don't display the alert, just direct them to the how to get A-EUR where the need for ETH is mentioned already)
- check /tryit on both rinkeby & main network.
- ...TBC
> Fix getting started

- src/containers/augmintToken/index.js
- src/modules/ethereum/metricsTransaction.js
- src/modules/metricsProvider.js
- src/modules/reducers/contracts.js
- src/modules/reducers/metrics.js
- src/modules/reducers/monetarySupervisor.js
- src/utils/constants.js
Go to `/stability` page
https://docs.google.com/document/d/1lL4RYlqrbyFvqGcDkemO-jj_W239_pfxWcwroi2CrqM/edit
> Stability board

- package.json
- src/components/ExchangeLinks.js
- src/components/dashboard/components/sideNav/index.js
- src/components/dashboard/containers/topNav/index.js
- src/components/hash/index.js
- src/components/navigation/index.js
- src/containers/augmintToken/index.js
- src/containers/home/NotConnectedHome/index.js
- src/containers/home/NotConnectedHome/member.js
- src/utils/bodyHelper.js
- check the site on mobile to see the site app menu and try to scroll the page while these menus are open
- pretty-quick pre-commit hook does not work - see the
> fix minor bugs

- package.json
- src/components/dashboard/containers/topNav/styles.js
- src/containers/app/index.js
- src/styles/global.js
- yarn.lock
> Greenkeeper/styled components 4.1.1

- src/containers/augmintToken/index.js
- src/containers/augmintToken/styles.js
- src/modules/ethereum/metricsTransaction.js
- src/modules/reducers/monetarySupervisor.js
go to [augmint.org/stability](https://www.augmint.org/stability) while connected to the main network.
> fix(monetarySupervisor): legacy metrics calculations & question marks in ETH metrics fixes

- src/modules/reducers/metrics.js
call metrics fetch tx-s in parallel for Stability Dashboard
loading of stability dashboard should be faster now
> Stability Dashboard page performance improvement

- package.json
- yarn.lock
> chore(pretty-quick-1.10.0): update

- package.json
- yarn.lock
> chore(react-script-2.1.5) update

- src/components/augmint-ui/icon/index.js
- src/components/dashboard/components/sideNav/index.js
check the navigation of the app
–
> feat(sideNav, icon): add send nav item & icon

- package.json
- yarn.lock
> chore(package): remove del dependency

- package.json
> fix(package.json): downgrade yarn to 1.13.0

- .travis.yml
- cypress/integration/exchange.js
- cypress/integration/loans.js
- cypress/support/commands.js
- src/components/Disclaimer.js
- src/containers/exchange/components/MatchMultipleOrdersButton.js
- src/containers/exchange/components/MyOrders.js
- src/containers/exchange/components/OrderBook.js
- src/containers/exchange/index.js
- src/modules/ethereum/exchangeTransactions.Matching.test.js
- src/modules/ethereum/exchangeTransactions.js
- src/modules/ethereum/exchangeTransactions.test.js
- src/modules/ethereum/gas.js
- src/modules/reducers/orders.js
Order matching matches all orders using Exchange contract's `matchMultipleOrders` fx.
> Multi order match

- .travis.yml
- package.json
> bump yarn version

- src/containers/home/concept/index.js
- go to augmint.org/concept
"A-EUR is the first Augmint token to be implemented. A-EUR will be targeted to EUR."
mondjuk erre:
"A-EUR is the first Augmint token implemented. A-EUR is targeted to EUR."
> fix(concept/index): change text

- README.md
github repo readme first aid (e.g "The first token ~~will be~~ A-EUR") + minimal facelift to
I will use this as template for the other repos
> readme first aid

- src/components/augmint-ui/currencies.js
merge fixes from redesign branch (#557)
> currencies component fixes

- package.json
- yarn.lock
It's in preparation to use augmint-js : align web3 versions so there won't be two different web3 package in the bundle.
Check web3 version on under-the-hood
> Upgrade to web3js beta36

- src/containers/exchange/components/PlaceOrderForm.js
- src/containers/funding/components/AddWithdrawForm.js
- src/containers/loan/newLoan/NewLoanForm.js
- src/containers/lock/containers/LockForm/index.js
- src/containers/transfer/components/TokenTransferForm.js
> field autofocus fixes

- src/containers/exchange/components/PlaceOrderForm.js
- src/containers/funding/components/AddWithdrawForm.js
- src/containers/loan/newLoan/NewLoanForm.js
- src/containers/lock/containers/LockForm/index.js
- src/containers/transfer/components/TokenTransferForm.js
> Forms: autofocus only on larger screens

- src/components/Table/index.js
- src/containers/account/components/TransferList.js
> fix: spurious "Show older" button on Exchange

- cypress/integration/loans.js
- src/components/augmint-ui/currencies.js
- src/containers/exchange/components/PlaceOrderForm.js
- src/containers/funding/components/AddWithdrawForm.js
- src/containers/loan/newLoan/NewLoanForm.js
- src/utils/constants.js
fixes #629
Should be fixed:
(tested on local)
> Use 5 decimals for Ethers

- .travis.yml
- package.json
- yarn.lock
`sha3` build  occasionally fails on travis  at `node-gyp rebuild`:
https://gist.github.com/szerintedmi/2b8ecc2344d92c52a4dd6c1e1e5bc408
Fix attempt based on [this thread](https://github.com/phusion/node-sha3/issues/32#issuecomment-490157571)
> Attempt to fix sha3 build occasionally failing on Travis

- src/components/MsgPanels.js
- src/containers/app/EthereumTxStatus.js
- src/containers/exchange/components/CancelOrderButton.js
> fix(EthSubmissionErrorPanel): delete unnec error content & fix styling

- package.json
- src/modules/augmintTokenProvider.js
- src/modules/ethereum/SolidityContract.js
- src/modules/ethereum/ethersHelper.js
- src/modules/ethereum/tradeTransactions.js
- src/modules/exchangeProvider.js
- src/modules/legacyBalancesProvider.js
- src/modules/loanManagerProvider.js
- src/modules/lockManagerProvider.js
- src/modules/preTokenProvider.js
- src/modules/ratesProvider.js
- src/modules/reducers/web3Connect.js
- src/modules/stabilityBoardProxyProvider.js
- yarn.lock
> fix notifications on mobile wallets

- src/containers/loan/collectLoan/CollectLoanButton.css
- src/containers/loan/collectLoan/CollectLoanButton.js
- src/containers/loan/collectLoan/index.js
- src/containers/loan/loanDetailsPage.js
- src/containers/loan/loanList/LoanCard.js
- src/containers/loan/loanList/index.js
- src/containers/loan/repayLoan/RepayLoanPage.js
> show collect button on uncollected loans - fixes #609

- src/containers/app/index.js
- src/containers/loan/repayLoan/RepayLoanPage.js
so loans can be repaid if `loan.repaymentAmount <= userAccount.tokenBalance`
> fix(RepayLoanPage) change loanAmount to repaymentAmount

- package.json
- src/containers/augmintToken/index.js
- src/containers/loan/components/LoanListDetails.js
* fix dateformat parse bug (on rates last updated timestamp)
> bugfixes for release 1.4 (margin-loan)

- cypress/integration/augmintbasic.js
- package.json
- src/.eslintrc
- src/components/PageLayout.js
- src/containers/underthehood/LoansInfoGroup.js
- src/containers/underthehood/components/ArrayDump.js
- src/containers/underthehood/components/LoanManagerInfo.js
- src/containers/underthehood/index.js
- src/modules/reducers/loans.js
- yarn.lock
under-the-hood page improvements:
- fix ArrayDump component output for certain augmint-js types
- copy to clipboard as json button for ArrayDump component
- add summary section to 'Loans' page
> under-the-hood-loan-page

- cypress/integration/augmintbasic.js
- package.json
- src/.eslintrc
- src/components/PageLayout.js
- src/containers/underthehood/LoansInfoGroup.js
- src/containers/underthehood/components/ArrayDump.js
- src/containers/underthehood/components/LoanManagerInfo.js
- src/containers/underthehood/index.js
- src/modules/reducers/loans.js
- yarn.lock
under-the-hood page improvements
* fix ArrayDump component output for certain augmint-js types
* copy to clipboard as json button for ArrayDump component
* add summary section to 'Loans' page
> Release 1.4.1

- src/components/augmint-ui/icon/index.js
- src/containers/loan/components/LoanListDetails.js
- src/containers/underthehood/LoansInfoGroup.js
- src/containers/underthehood/components/LoanManagerInfo.js
- src/modules/loanManagerProvider.js
Netlify deploys started to [fail on compiler](https://app.netlify.com/sites/augmint/deploys/5f5762caaeb393009175374a) warnings. 
The following warnings are resolved to make deploy time compile pass:
```
Treating warnings as errors because process.env.CI = true.
Most CI servers set it automatically.
Failed to compile.
./src/containers/loan/components/LoanListDetails.js
Line 2:  'NavLink' is defined but never used  no-unused-vars
./src/containers/underthehood/components/LoanManagerInfo.js
Line 4:  'Tokens' is defined but never used  no-unused-vars
./src/containers/underthehood/LoansInfoGroup.js
Line 5:  'stringify' is defined but never used  no-unused-vars
./src/modules/loanManagerProvider.js
Line 8:  'fetchAllLoans' is defined but never used  no-unused-vars …
```
> fix compiler warnings

- package.json
- public/index.html
- src/components/augmint-ui/icon/index.js
- src/containers/loan/components/AddCollateralButton.js
- src/containers/loan/components/LoanListDetails.js
- src/containers/loan/loanList/LoanCard.js
- src/containers/underthehood/LoansInfoGroup.js
- src/containers/underthehood/components/LoanManagerInfo.js
- src/modules/ethereum/gas.js
- src/modules/loanManagerProvider.js
- yarn.lock
- top-up collateral is always shown ( not only when collateralization is below threshold) (#725 )
- increased default gas limit for loan repay tx (#733 )
- fixed minor compiler warnings (#734 )
> Release v1.4.2
